name: Backend CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy
        run: |
          curl -X POST https://api.render.com/deploy/srv-xxxxxxxxxx \
          -H 'Authorization: Bearer ${{ secrets.RENDER_API_KEY }}'